# Generated by Django 5.0.1 on 2024-05-03 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_coverimage_user_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuideRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname_khmer', models.CharField(max_length=30)),
                ('fullname_english', models.CharField(max_length=30)),
                ('cv', models.FileField(max_length=1000, upload_to='files/guide_register_info/')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('tour_place_coordinate', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
