# Generated by Django 5.0.1 on 2024-06-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_tourguideregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourguideregistration',
            old_name='tour_place_coordinate',
            new_name='google_map_url',
        ),
    ]
