# Generated by Django 5.0.1 on 2024-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_tour_place_coordinate_tourguideregistration_google_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguideregistration',
            name='google_map_url',
            field=models.CharField(max_length=255),
        ),
    ]
