# Generated by Django 5.0.1 on 2024-06-30 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_tourguideregistration_google_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguideregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourguideregistration',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
