# Generated by Django 5.0.1 on 2024-07-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_tourguideregistration_created_at_and_more'),
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegrambot.telegramaccount'),
        ),
    ]
