# Generated by Django 5.0.1 on 2024-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role',
            name='kh_name',
            field=models.CharField(default='អតិថិជន', max_length=30),
            preserve_default=False,
        ),
    ]
