# Generated by Django 5.0.1 on 2024-07-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramaccount',
            old_name='last_bot_response',
            new_name='last_message',
        ),
    ]
