# Generated by Django 5.0.1 on 2024-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_rename_last_bot_response_telegramaccount_last_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramaccount',
            old_name='last_message',
            new_name='last_bot_message',
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_user_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
