# Generated by Django 5.0.1 on 2024-07-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_rename_last_message_telegramaccount_last_bot_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
