# Generated by Django 5.0.1 on 2024-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_alter_telegramaccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_bot_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_user_response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
