# Generated by Django 5.0.1 on 2024-04-30 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30, unique=True)),
                ('percentage_of_sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('percentage_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tour_place_coordinate', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_close', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='package_favorites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour_package.packagecategory')),
                ('commission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour_package.packagecommission')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to='images/package_images/')),
                ('type', models.CharField(choices=[('normal', 'normal'), ('thumbnail', 'thumbnail'), ('cover', 'cover')], default='normal', max_length=30)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('is_close', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageUnavailableDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unavailable_at', models.DateField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.package')),
            ],
        ),
    ]
