# Generated by Django 5.0.1 on 2024-05-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagecategory',
            table='package_category',
        ),
    ]
