# Generated by Django 5.0.1 on 2024-05-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0002_alter_packagecategory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagecategory',
            table='tour_package_package_category',
        ),
        migrations.AlterModelTable(
            name='packagecommission',
            table='tour_package_package_commission',
        ),
        migrations.AlterModelTable(
            name='packageimage',
            table='tour_package_package_image',
        ),
        migrations.AlterModelTable(
            name='packageschedule',
            table='tour_package_package_schedule',
        ),
        migrations.AlterModelTable(
            name='packageservice',
            table='tour_package_package_service',
        ),
        migrations.AlterModelTable(
            name='packageunavailabledate',
            table='tour_package_package_unavailable_date',
        ),
    ]
