# Generated by Django 5.0.1 on 2024-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0004_packagechargetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='location_url',
            field=models.URLField(max_length=2000),
        ),
    ]
