# Generated by Django 5.0.1 on 2024-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0005_alter_package_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecategory',
            name='kh_name',
            field=models.CharField(default='ប្រាសាទ', max_length=30),
            preserve_default=False,
        ),
    ]
