# Generated by Django 5.0.1 on 2024-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='payment_intent_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
